# Codi Per Concatenar data sbd centre

Importació del dataframe desde 2008 a 2018

In [27]:
import pandas as pd

df_2008 = pd.read_csv('meteosabadell_2008-05_to_2018-01.csv')
df_2008.head()

,date,year,month,day,max,min,avg,dep_from_normal,dew_point,wet_bulb,...,cooling,sig_cond,sun_hrs,snow_fall,rain,pressure,wind_speed,wind_dir,wind_max,wind_max_dir
0,2008-05-01,2008,5,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2008-05-02,2008,5,2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,HOT,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2008-05-03,2008,5,3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,HOT,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2008-05-04,2008,5,4,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,HOT,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2008-05-05,2008,5,5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,HOT,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN

Importació del dataframe desde 2018 a 2026

In [11]:
df_2018 = pd.read_csv('meteosabadell_2018-01_to_2026-01.csv')
df_2018.head()

,date,year,month,day,source_format,source_url,mean_temp_c,max_temp_c,max_temp_time,min_temp_c,min_temp_time,heat_deg_days,cool_deg_days,rain_mm,avg_wind_kmh,max_wind_kmh,max_wind_time,dom_wind_dir
0,2018-02-01,2018,2,1,txt_noaa,http://www.meteosabadell.cat/www/NOAA/2018/Feb...,7.1,9.4,12:14,4.8,21:39,11.2,0.0,5.4,2.9,20.9,22:15,NNE
1,2018-02-02,2018,2,2,txt_noaa,http://www.meteosabadell.cat/www/NOAA/2018/Feb...,6.8,10.7,15:30,5.1,03:20,11.5,0.0,0.0,3.4,22.5,13:26,NNE
2,2018-02-03,2018,2,3,txt_noaa,http://www.meteosabadell.cat/www/NOAA/2018/Feb...,7.3,11.7,12:40,1.9,06:01,11.0,0.0,0.0,4.3,27.4,13:25,W
3,2018-02-04,2018,2,4,txt_noaa,http://www.meteosabadell.cat/www/NOAA/2018/Feb...,6.4,7.4,10:59,5.2,22:46,11.9,0.0,10.0,4.3,29.0,21:37,N
4,2018-02-05,2018,2,5,txt_noaa,http://www.meteosabadell.cat/www/NOAA/2018/Feb...,6.9,8.7,13:00,4.9,01:03,11.3,0.0,28.2,5.1,22.5,04:17,N

In [ ]:
df_2008.rename(columns = {'max':'T_max','min':'T_min','avg':'T_avg', 'rain':'rain_mm','wind_speed':'avg_wind_kmh','wind_max':'max_wind_kmh'}, inplace = True)
df_2018.rename(columns = {'max_temp_c':'T_max','min_temp_c':'T_min','mean_temp_c':'T_avg','dom_wind_dir':'wind_dir'}, inplace = True)

df_2008.drop(columns = ['dew_point','wet_bulb','cooling','sun_hrs','snow_fall','pressure','sig_cond'],axis = 1, inplace = True)
df_2018.drop(columns = ['source_format','source_url','max_temp_time','min_temp_time','heat_deg_days','cool_deg_days','max_wind_time'],axis = 1, inplace = True)

In [36]:
df_2008.head()

,date,year,month,day,T_max,T_min,T_avg,dep_from_normal,heating,rain_mm,avg_wind_kmh,wind_dir,max_wind_kmh,wind_max_dir
0,2008-05-01,2008,5,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2008-05-02,2008,5,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2008-05-03,2008,5,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2008-05-04,2008,5,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2008-05-05,2008,5,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
df_2018.head()

,date,year,month,day,T_avg,T_max,T_min,rain_mm,avg_wind_kmh,max_wind_kmh,wind_dir
0,2018-02-01,2018,2,1,7.1,9.4,4.8,5.4,2.9,20.9,NNE
1,2018-02-02,2018,2,2,6.8,10.7,5.1,0.0,3.4,22.5,NNE
2,2018-02-03,2018,2,3,7.3,11.7,1.9,0.0,4.3,27.4,W
3,2018-02-04,2018,2,4,6.4,7.4,5.2,10.0,4.3,29.0,N
4,2018-02-05,2018,2,5,6.9,8.7,4.9,28.2,5.1,22.5,N

In [40]:
df_2008.drop(columns = ['dep_from_normal','heating','wind_max_dir'], axis = 1, inplace = True)

,date,year,month,day,T_max,T_min,T_avg,rain_mm,avg_wind_kmh,wind_dir,max_wind_kmh
0,2008-05-01,2008,5,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2008-05-02,2008,5,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2008-05-03,2008,5,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2008-05-04,2008,5,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2008-05-05,2008,5,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
3250,NaN,2017,2,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3251,NaN,2017,4,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3252,NaN,2017,6,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3253,NaN,2017,9,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3254,NaN,2017,11,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
df_2018['date'].isna().sum()

0

In [52]:
df_2008 = df_2008.dropna(subset = ['date'])
df_2008.tail(10)

,date,year,month,day,T_max,T_min,T_avg,rain_mm,avg_wind_kmh,wind_dir,max_wind_kmh
3189,2018-01-22,2018,1,22,19.0,10.9,13.8,0.0,3.6,347.0,22.2
3190,2018-01-23,2018,1,23,18.3,8.9,12.3,0.0,2.8,328.0,18.5
3191,2018-01-24,2018,1,24,18.3,6.7,11.7,0.0,1.9,227.0,16.6
3192,2018-01-25,2018,1,25,13.3,8.9,11.2,0.2,2.2,218.0,14.8
3193,2018-01-26,2018,1,26,11.3,6.1,7.8,48.2,4.2,335.0,33.3
3194,2018-01-27,2018,1,27,12.3,5.6,8.8,0.0,2.3,353.0,18.5
3195,2018-01-28,2018,1,28,17.4,8.3,11.7,0.0,2.3,237.0,16.6
3196,2018-01-29,2018,1,29,16.7,6.2,11.0,0.0,2.8,289.0,18.5
3197,2018-01-30,2018,1,30,17.2,4.7,9.6,0.0,2.5,166.0,20.4
3198,2018-01-31,2018,1,31,16.8,4.3,9.7,0.0,3.1,250.0,24.1

In [54]:
df_2018.head()

,date,year,month,day,T_avg,T_max,T_min,rain_mm,avg_wind_kmh,max_wind_kmh,wind_dir
0,2018-02-01,2018,2,1,7.1,9.4,4.8,5.4,2.9,20.9,NNE
1,2018-02-02,2018,2,2,6.8,10.7,5.1,0.0,3.4,22.5,NNE
2,2018-02-03,2018,2,3,7.3,11.7,1.9,0.0,4.3,27.4,W
3,2018-02-04,2018,2,4,6.4,7.4,5.2,10.0,4.3,29.0,N
4,2018-02-05,2018,2,5,6.9,8.7,4.9,28.2,5.1,22.5,N

In [88]:
df_2008.groupby('year')

,date,month,day,T_max,T_min,T_avg,rain_mm,avg_wind_kmh,wind_dir,max_wind_kmh
year,,,,,,,,,,
2008,2008-05-012008-05-022008-05-032008-05-042008-0...,2082,3875,3677.9,2025.5,2673.5,198.6,450.2,22024.0,2595.9
2009,2009-01-012009-01-022009-01-032009-01-042009-0...,2382,5738,7656.2,4500.6,5918.2,492.3,1200.7,68767.0,7069.3
2010,2010-01-012010-01-022010-01-032010-01-042010-0...,1291,2449,2726.6,1524.7,2058.9,208.2,551.1,30988.0,2863.8
2011,2011-01-012011-01-022011-01-032011-01-042011-0...,1985,4777,6193.1,3560.8,4718.5,518.1,1168.0,57092.0,6023.8
2012,2012-01-012012-01-022012-01-032012-01-042012-0...,2167,5271,6988.4,3917.0,5305.3,385.3,1373.5,70072.0,7061.7
2013,2013-01-012013-01-022013-01-032013-01-042013-0...,2134,5242,6701.9,3811.2,5088.6,464.3,1445.7,68402.0,7438.6
2014,2014-01-012014-01-022014-01-032014-01-042014-0...,2382,5738,7889.8,4758.4,6140.6,592.7,1492.9,70173.0,7800.9
2015,2015-01-012015-01-022015-01-032015-01-042015-0...,2382,5738,7634.4,4487.6,5883.8,278.8,1352.0,67537.0,7130.5
2016,2016-01-012016-01-022016-01-032016-01-042016-0...,2204,5302,6947.8,4170.9,5415.9,329.7,1304.3,63986.0,6726.5
2017,2017-01-012017-01-022017-01-032017-01-042017-0...,2382,5738,7658.8,4368.2,5842.6,417.9,1489.0,67182.0,8873.4
2018,2018-01-012018-01-022018-01-032018-01-042018-0...,31,496,475.3,221.9,333.0,67.9,122.5,8014.0,790.2

In [117]:
nan_per_year = df_2018.groupby('year')['T_avg'].apply(lambda x: x.isna().sum())
nan_per_year

year
2018    0
2019    0
2020    0
2021    0
2022    0
2023    0
2024    0
2025    0
2026    0
Name: T_avg, dtype: int64

In [119]:
not_nan_per_year = df_2018.groupby('year')['T_avg'].apply(lambda x: x.notna().sum())
not_nan_per_year

year
2018    303
2019    333
2020    335
2021    365
2022    353
2023    350
2024    360
2025    365
2026     31
Name: T_avg, dtype: int64

In [121]:
df_2008 = df_2008.dropna(subset = ['T_avg'])

In [142]:
df_2008.tail()

,date,year,month,day,T_max,T_min,T_avg,rain_mm,avg_wind_kmh,wind_dir,max_wind_kmh
3194,2018-01-27,2018,1,27,12.3,5.6,8.8,0.0,2.3,353.0,18.5
3195,2018-01-28,2018,1,28,17.4,8.3,11.7,0.0,2.3,237.0,16.6
3196,2018-01-29,2018,1,29,16.7,6.2,11.0,0.0,2.8,289.0,18.5
3197,2018-01-30,2018,1,30,17.2,4.7,9.6,0.0,2.5,166.0,20.4
3198,2018-01-31,2018,1,31,16.8,4.3,9.7,0.0,3.1,250.0,24.1

In [144]:
df_2018.head()

,date,year,month,day,T_avg,T_max,T_min,rain_mm,avg_wind_kmh,max_wind_kmh,wind_dir
0,2018-02-01,2018,2,1,7.1,9.4,4.8,5.4,2.9,20.9,NNE
1,2018-02-02,2018,2,2,6.8,10.7,5.1,0.0,3.4,22.5,NNE
2,2018-02-03,2018,2,3,7.3,11.7,1.9,0.0,4.3,27.4,W
3,2018-02-04,2018,2,4,6.4,7.4,5.2,10.0,4.3,29.0,N
4,2018-02-05,2018,2,5,6.9,8.7,4.9,28.2,5.1,22.5,N

In [191]:
df_sbd_centre = pd.concat([df_2008,df_2018])

In [220]:
df_sbd_centre[['wind_dir']]

     wind_dir
5         0.0
6         0.0
7         0.0
21        0.0
22        0.0
...       ...
2790       SW
2791        W
2792      WSW
2793        W
2794        W

[5834 rows x 1 columns]

In [222]:
import pandas as pd
import numpy as np

dir_to_deg = {
    'N': 0.0,
    'NNE': 22.5,
    'NE': 45.0,
    'ENE': 67.5,
    'E': 90.0,
    'ESE': 112.5,
    'SE': 135.0,
    'SSE': 157.5,
    'S': 180.0,
    'SSW': 202.5,
    'SW': 225.0,
    'WSW': 247.5,
    'W': 270.0,
    'WNW': 292.5,
    'NW': 315.0,
    'NNW': 337.5
}

def convert_wind_dir(x):
    if pd.isna(x):
        return np.nan
    
    # Si ja és numèric, el deixem com float
    if isinstance(x, (int, float, np.integer, np.floating)):
        return float(x)
    
    # Si és string, netegem espais
    x = str(x).strip().upper()
    
    # Si és una direcció cardinal
    if x in dir_to_deg:
        return dir_to_deg[x]
    
    # Si és un número guardat com string
    try:
        return float(x)
    except ValueError:
        return np.nan

df_sbd_centre['wind_dir_deg'] = df_sbd_centre['wind_dir'].apply(convert_wind_dir)

In [224]:
df_sbd_centre[df_sbd_centre['wind_dir_deg'].isna()]['wind_dir'].unique()

array([], dtype=object)

In [226]:
df_sbd_centre['wind_dir'] = df_sbd_centre['wind_dir'].apply(convert_wind_dir)

In [232]:
df_sbd_centre.drop(columns = ['wind_dir_deg'], axis = 1, inplace = True)

In [234]:
df_sbd_centre.head()

,date,year,month,day,T_max,T_min,T_avg,rain_mm,avg_wind_kmh,wind_dir,max_wind_kmh
5,2008-05-06,2008,5,6,16.8,14.6,16.7,0.0,1.3,0.0,5.6
6,2008-05-07,2008,5,7,27.0,13.8,19.4,0.0,4.4,0.0,20.4
7,2008-05-08,2008,5,8,16.5,12.5,13.9,0.0,2.1,0.0,7.4
21,2008-05-22,2008,5,22,20.5,13.3,15.8,0.0,4.9,0.0,14.8
22,2008-05-23,2008,5,23,26.2,13.9,18.7,2.0,2.1,0.0,9.3

In [ ]:
df_sbd_centre.to_csv('Meteosabadell_cleaned_data.csv')

# Netejar Dades Vacarisses

In [24]:
import pandas as pd

url_vacarisses = 'https://raw.githubusercontent.com/DavidDDRC99/VO-evolution/refs/heads/main/Raw%20Data/Vacarisses_data.csv'
url_sbd_nord = 'https://raw.githubusercontent.com/DavidDDRC99/VO-evolution/refs/heads/main/Raw%20Data/Sbd_nord_data.csv'

df_vacarisses = pd.read_csv(url_vacarisses)
df_sbd_nord = pd.read_csv(url_sbd_nord) 
df_sbd_nord.head()

,datetime_utc,temp_mean (°C),temp_max (°C),temp_min (°C),humidity (%),precip (mm),wind_max_10m (km/h),pressure (hPa),radiation (W/m²),station_code,wind_mean_10m (km/h),wind_dir_10m (degrees)
0,2008-10-24 00:00:00,11.9,12.0,11.9,88,0.0,11.2,1022.0,0.0,XF,NaN,NaN
1,2008-10-24 00:30:00,11.9,12.0,11.9,89,0.0,6.1,1022.0,0.0,XF,NaN,NaN
2,2008-10-24 01:00:00,11.8,12.0,11.7,90,0.0,5.0,1022.0,0.0,XF,NaN,NaN
3,2008-10-24 01:30:00,11.6,11.7,11.5,91,0.0,8.6,1022.0,0.0,XF,NaN,NaN
4,2008-10-24 02:00:00,11.7,12.0,11.5,88,0.0,9.0,1021.0,0.0,XF,NaN,NaN

In [25]:
df_vacarisses.rename(columns = {'temp_mean (°C)':'T_avg','temp_min (°C)':'T_min','temp_max (°C)':'T_max',
                                'wind_dir_10m (degrees)':'wind_dir','precip (mm)':'rain_mm',
                                'wind_max_10m (km/h)':'max_wind_kmh','wind_mean_10m (km/h)':'avg_wind_kmh'}, inplace = True)

df_sbd_nord.rename(columns = {'temp_mean (°C)':'T_avg','temp_min (°C)':'T_min','temp_max (°C)':'T_max',
                                'wind_dir_10m (degrees)':'wind_dir','precip (mm)':'rain_mm',
                                'wind_max_10m (km/h)':'max_wind_kmh','wind_mean_10m (km/h)':'avg_wind_kmh'}, inplace = True)

df_vacarisses.drop(columns = ['station_code'], inplace = True)
df_sbd_nord.drop(columns = ['station_code'], inplace = True)

df_vacarisses.head()
df_sbd_nord.head()

,datetime_utc,T_avg,T_max,T_min,humidity (%),rain_mm,max_wind_kmh,pressure (hPa),radiation (W/m²),avg_wind_kmh,wind_dir
0,2008-10-24 00:00:00,11.9,12.0,11.9,88,0.0,11.2,1022.0,0.0,NaN,NaN
1,2008-10-24 00:30:00,11.9,12.0,11.9,89,0.0,6.1,1022.0,0.0,NaN,NaN
2,2008-10-24 01:00:00,11.8,12.0,11.7,90,0.0,5.0,1022.0,0.0,NaN,NaN
3,2008-10-24 01:30:00,11.6,11.7,11.5,91,0.0,8.6,1022.0,0.0,NaN,NaN
4,2008-10-24 02:00:00,11.7,12.0,11.5,88,0.0,9.0,1021.0,0.0,NaN,NaN

In [26]:
percent_nan = df_sbd_nord.isna().mean() * 100
percent_nan

datetime_utc        0.000000
T_avg               0.000000
T_max               0.009160
T_min               0.008833
humidity (%)        0.000000
rain_mm             0.000000
max_wind_kmh        0.024864
pressure (hPa)      0.000000
radiation (W/m²)    0.000000
avg_wind_kmh        3.546378
wind_dir            3.554557
dtype: float64

D'aquí veiem que la majoria de les dades de vent son NaN, per tant no agafarem aquestes dades ---> dropegem

In [27]:
df_vacarisses.drop(columns=['wind_dir','max_wind_kmh', 'avg_wind_kmh'], inplace = True)

In [28]:
df_vacarisses['datetime_utc'] = pd.to_datetime(df_vacarisses['datetime_utc'])
df_sbd_nord['datetime_utc'] = pd.to_datetime(df_sbd_nord['datetime_utc'])

In [29]:
df_vacarisses.info()
df_sbd_nord.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525936 entries, 0 to 525935
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   datetime_utc      525936 non-null  datetime64[ns]
 1   T_avg             525013 non-null  float64
 2   T_max             333417 non-null  float64
 3   T_min             333424 non-null  float64
 4   humidity (%)      523631 non-null  float64
 5   rain_mm           524474 non-null  float64
 6   pressure (hPa)    524584 non-null  float64
 7   radiation (W/m²)  285218 non-null  float64
dtypes: datetime64[ns](1), float64(7)
memory usage: 32.1 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 305664 entries, 0 to 305663
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   datetime_utc      305664 non-null  datetime64[ns]
 1   T_avg             305664 non-null  float64
 2   T_max             305636 non-null  float64
 3   T_min             305637 non-null  float64
 4   humidity (%)      305664 non-null  int64
 5   rain_mm           305664 non-null  float64
 6   max_wind_kmh      305588 non-null  float64
 7   pressure (hPa)    305664 non-null  float64
 8   radiation (W/m²)  305664 non-null  float64
 9   avg_wind_kmh      294824 non-null  float64
 10  wind_dir          294799 non-null  float64
dtypes: datetime64[ns](1), float64(9), int64(1)
memory usage: 25.7 MB

In [ ]:
df_vacarisses.to_csv("Cleaned Data/Vacarisses_hourly.csv", index=False)
df_sbd_nord.to_csv("Cleaned Data/Sbd_nord_hourly.csv", index=False)

# Transformació de les dades de Vacarisses: Horari ---> Diari

In [2]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/DavidDDRC99/VO-evolution/refs/heads/main/Data/Vacarisses_data.csv')
df.head()

,datetime_utc,temp_mean (°C),temp_max (°C),temp_min (°C),humidity (%),precip (mm),wind_mean_10m (km/h),wind_dir_10m (degrees),wind_max_10m (km/h),pressure (hPa),radiation (W/m²),station_code
0,1996-02-16 00:00:00,-2.0,NaN,NaN,99.0,0.0,0.0,48.0,NaN,1028.2,0.0,D2
1,1996-02-16 00:30:00,-2.1,NaN,NaN,99.0,0.0,1.1,9.0,NaN,1028.2,0.0,D2
2,1996-02-16 01:00:00,-2.3,NaN,NaN,99.0,0.0,0.0,33.0,NaN,1028.3,0.0,D2
3,1996-02-16 01:30:00,-2.5,NaN,-2.6,99.0,0.0,0.0,120.0,NaN,1028.3,0.0,D2
4,1996-02-16 02:00:00,-2.2,NaN,NaN,99.0,0.0,1.4,125.0,NaN,1027.2,0.0,D2

In [3]:
df.drop(columns = ['station_code'], inplace = True)
df.head()

,datetime_utc,temp_mean (°C),temp_max (°C),temp_min (°C),humidity (%),precip (mm),wind_mean_10m (km/h),wind_dir_10m (degrees),wind_max_10m (km/h),pressure (hPa),radiation (W/m²)
0,1996-02-16 00:00:00,-2.0,NaN,NaN,99.0,0.0,0.0,48.0,NaN,1028.2,0.0
1,1996-02-16 00:30:00,-2.1,NaN,NaN,99.0,0.0,1.1,9.0,NaN,1028.2,0.0
2,1996-02-16 01:00:00,-2.3,NaN,NaN,99.0,0.0,0.0,33.0,NaN,1028.3,0.0
3,1996-02-16 01:30:00,-2.5,NaN,-2.6,99.0,0.0,0.0,120.0,NaN,1028.3,0.0
4,1996-02-16 02:00:00,-2.2,NaN,NaN,99.0,0.0,1.4,125.0,NaN,1027.2,0.0

In [4]:
import pandas as pd
import numpy as np

# 1. Assegurar datetime
df["datetime_utc"] = pd.to_datetime(df["datetime_utc"], errors="coerce")

# 2. Funció per direcció del vent (important!)
def mean_wind_dir(deg):
    deg = deg.dropna()
    if len(deg) == 0:
        return np.nan
    rad = np.deg2rad(deg)
    sin_mean = np.mean(np.sin(rad))
    cos_mean = np.mean(np.cos(rad))
    return np.rad2deg(np.arctan2(sin_mean, cos_mean)) % 360

# 3. Agregació diària
daily_df = (
    df.groupby(df["datetime_utc"].dt.floor("D"))
      .agg(
          T_avg=("temp_mean (°C)", "mean"),
          T_max=("temp_max (°C)", "max"),
          T_min=("temp_min (°C)", "min"),
          humidity_avg=("humidity (%)", "mean"),
          precip_total=("precip (mm)", "sum"),
          wind_avg=("wind_mean_10m (km/h)", "mean"),
          wind_dir=("wind_dir_10m (degrees)", mean_wind_dir),
          wind_max=("wind_max_10m (km/h)", "max"),
          pressure_avg=("pressure (hPa)", "mean"),
          radiation_avg=("radiation (W/m²)", "mean"),
      )
      .reset_index()
)

# 4. Rename columna data
daily_df = daily_df.rename(columns={"datetime_utc": "date"})

In [6]:
daily_df['radiation_avg'].isna().sum()

5000

In [7]:
daily_df.rename(columns = {'precip_total':'rain_mm', 'wind_avg':'avg_wind_kmh','wind_max':'max_wind_kmh'}, inplace = True)

In [8]:
nan_percent = daily_df.isna().mean() * 100

print(nan_percent)

date              0.000000
T_avg             0.000000
T_max             0.346715
T_min             0.383212
humidity_avg      0.145985
rain_mm           0.000000
avg_wind_kmh     74.041971
wind_dir         73.877737
max_wind_kmh     63.202555
pressure_avg      0.082117
radiation_avg    45.620438
dtype: float64

In [9]:
daily_df.drop(columns=['radiation_avg','max_wind_kmh','wind_dir','avg_wind_kmh'], inplace=True)

In [ ]:
daily_df.to_csv('./Data/Vacarisses_daily_data.csv', index=False)

!git add ./Data/Vacarisses_daily_data.csv
!git commit -m "Add Vacarisses daily data CSV"
!git push

[main 06c153c] Add Vacarisses daily data CSV
 1 file changed, 10961 insertions(+)
 create mode 100644 Data/Vacarisses_daily_data.csv

To https://github.com/DavidDDRC99/VO-evolution.git
   f9f3bc9..06c153c  main -> main

# Transformació de les dades de SBD parc agrari: Horari ---> Diari

In [ ]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/DavidDDRC99/VO-evolution/refs/heads/main/Data/Sabadell_Parc_agrari_data.csv')
df.head()

,datetime_utc,temp_mean (°C),temp_max (°C),temp_min (°C),humidity (%),precip (mm),wind_mean_10m (km/h),wind_dir_10m (degrees),wind_max_10m (km/h),pressure (hPa),radiation (W/m²),station_code
0,1996-02-16 00:00:00,-2.0,NaN,NaN,99.0,0.0,0.0,48.0,NaN,1028.2,0.0,D2
1,1996-02-16 00:30:00,-2.1,NaN,NaN,99.0,0.0,1.1,9.0,NaN,1028.2,0.0,D2
2,1996-02-16 01:00:00,-2.3,NaN,NaN,99.0,0.0,0.0,33.0,NaN,1028.3,0.0,D2
3,1996-02-16 01:30:00,-2.5,NaN,-2.6,99.0,0.0,0.0,120.0,NaN,1028.3,0.0,D2
4,1996-02-16 02:00:00,-2.2,NaN,NaN,99.0,0.0,1.4,125.0,NaN,1027.2,0.0,D2

In [12]:
df.drop(columns = ['station_code'], inplace = True)

In [13]:
import pandas as pd
import numpy as np

# 1. Assegurar datetime
df["datetime_utc"] = pd.to_datetime(df["datetime_utc"], errors="coerce")

# 2. Funció per direcció del vent (important!)
def mean_wind_dir(deg):
    deg = deg.dropna()
    if len(deg) == 0:
        return np.nan
    rad = np.deg2rad(deg)
    sin_mean = np.mean(np.sin(rad))
    cos_mean = np.mean(np.cos(rad))
    return np.rad2deg(np.arctan2(sin_mean, cos_mean)) % 360

# 3. Agregació diària
daily_df = (
    df.groupby(df["datetime_utc"].dt.floor("D"))
      .agg(
          T_avg=("temp_mean (°C)", "mean"),
          T_max=("temp_max (°C)", "max"),
          T_min=("temp_min (°C)", "min"),
          humidity_avg=("humidity (%)", "mean"),
          precip_total=("precip (mm)", "sum"),
          wind_avg=("wind_mean_10m (km/h)", "mean"),
          wind_dir=("wind_dir_10m (degrees)", mean_wind_dir),
          wind_max=("wind_max_10m (km/h)", "max"),
          pressure_avg=("pressure (hPa)", "mean"),
          radiation_avg=("radiation (W/m²)", "mean"),
      )
      .reset_index()
)

# 4. Rename columna data
daily_df = daily_df.rename(columns={"datetime_utc": "date"})

In [14]:
daily_df['radiation_avg'].isna().sum()
nan_percent = daily_df.isna().mean() * 100

print(nan_percent)

date              0.000000
T_avg             0.000000
T_max             0.346715
T_min             0.383212
humidity_avg      0.145985
precip_total      0.000000
wind_avg         74.041971
wind_dir         73.877737
wind_max         63.202555
pressure_avg      0.082117
radiation_avg    45.620438
dtype: float64

In [23]:
import git


daily_df.to_csv('./Data/sbd_daily_data.csv', index=False)
daily_df.to_csv('./Data/sbd_daily_data.csv', index=False)

!git add ./Data/sbd_daily_data.csv
!git commit -m "Add SBD parc daily data CSV"
!git push

On branch main
Your branch and 'origin/main' have diverged,
and have 2 and 1 different commits each, respectively.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   data_preparation.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

To https://github.com/DavidDDRC99/VO-evolution.git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/DavidDDRC99/VO-evolution.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. If you want to integrate the remote changes,
hint: use 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.